#ifndef T1_EASING_H
#define T1_EASING_H

#include "T1_stdint.h"

typedef enum : u8 {
    EASINGTYPE_NONE = 0,
    EASINGTYPE_ALWAYS_1,
    EASINGTYPE_INOUT_SINE,
    EASINGTYPE_OUT_QUADRATIC,
    EASINGTYPE_EASEOUT_ELASTIC_ZERO_TO_ONE,
    EASINGTYPE_SINGLE_BOUNCE_ZERO_TO_ZERO,
    EASINGTYPE_DOUBLE_BOUNCE_ZERO_TO_ZERO,
    EASINGTYPE_QUADRUPLE_BOUNCE_ZERO_TO_ZERO,
    EASINGTYPE_OCTUPLE_BOUNCE_ZERO_TO_ZERO,
    EASINGTYPE_SINGLE_PULSE_ZERO_TO_ZERO,
    EASINGTYPE_OCTUPLE_PULSE_ZERO_TO_ZERO,
    EASINGTYPE_OUTOFBOUNDS
} T1EasingType;

f32 T1_easing_t_to_eased_t(
    const f32 t,
    const T1EasingType easing_type);

#endif // T1_EASINGTYPE_H


