#ifndef T1_EASING_H
#define T1_EASING_H

#include "T1_stdint.h"

typedef enum : u8 {
    T1_EASINGTYPE_NONE = 0,
    T1_EASINGTYPE_ALWAYS_1,
    T1_EASINGTYPE_INOUT_SINE,
    T1_EASINGTYPE_OUT_QUADRATIC,
    T1_EASINGTYPE_EASEOUT_ELASTIC_ZERO_TO_ONE,
    T1_EASINGTYPE_SINGLE_BOUNCE_ZERO_TO_ZERO,
    T1_EASINGTYPE_DOUBLE_BOUNCE_ZERO_TO_ZERO,
    T1_EASINGTYPE_QUADRUPLE_BOUNCE_ZERO_TO_ZERO,
    T1_EASINGTYPE_OCTUPLE_BOUNCE_ZERO_TO_ZERO,
    T1_EASINGTYPE_SINGLE_PULSE_ZERO_TO_ZERO,
    T1_EASINGTYPE_OCTUPLE_PULSE_ZERO_TO_ZERO,
    T1_EASINGTYPE_OUTOFBOUNDS
} T1EasingType;

f32 T1_easing_t_to_eased_t(
    const f32 t,
    const T1EasingType easing_type);

#endif // T1_EASING_H


